# Generated by Django 5.0.3 on 2024-03-19 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='estrelas',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
